/**
 * Plugins Index (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * To add a new integration:
 * 1. Create a new directory in plugins/ (e.g., plugins/my-integration/)
 * 2. Add your plugin files (index.tsx, steps/, codegen/, etc.)
 * 3. Run: pnpm discover-plugins (or it runs automatically on build)
 *
 * To remove an integration:
 * 1. Delete the plugin directory
 * 2. Run: pnpm discover-plugins (or it runs automatically on build)
 *
 * Discovered plugins: ai-gateway, firecrawl, linear, resend, slack, v0, ext:aws, ext:azure, ext:gcp, ext:lead-scraper, ext:mongodb, ext:redis
 */

import "./ai-gateway";
import "./firecrawl";
import "./linear";
import "./resend";
import "./slack";
import "./v0";

// Fork-specific extension plugins
import "@/extensions/plugins/aws";
import "@/extensions/plugins/azure";
import "@/extensions/plugins/gcp";
import "@/extensions/plugins/lead-scraper";
import "@/extensions/plugins/mongodb";
import "@/extensions/plugins/redis";

export type { IntegrationPlugin, PluginAction, ActionWithFullId } from "./registry";

// Export the registry utilities
export {
  computeActionId,
  findActionById,
  generateAIActionPrompts,
  getActionsByCategory,
  getAllActions,
  getAllDependencies,
  getAllEnvVars,
  getAllIntegrations,
  getCredentialMapping,
  getDependenciesForActions,
  getIntegration,
  getIntegrationLabels,
  getIntegrationTypes,
  getPluginEnvVars,
  getSortedIntegrationTypes,
  parseActionId,
  registerIntegration,
} from "./registry";
