/**
 * Step Registry (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * This registry enables dynamic step imports that are statically analyzable
 * by the bundler. Each action type maps to its step importer function.
 *
 * Generated entries: 21
 */

import "server-only";

// biome-ignore lint/suspicious/noExplicitAny: Dynamic step module types
type StepModule = Record<string, (input: any) => Promise<any>>;

export type StepImporter = {
  importer: () => Promise<StepModule>;
  stepFunction: string;
};

/**
 * Plugin step importers - maps action types to their step import functions
 * These imports are statically analyzable by the bundler
 */
export const PLUGIN_STEP_IMPORTERS: Record<string, StepImporter> = {
  "Generate Text": {
    importer: () => import("@/plugins/ai-gateway/steps/generate-text/step"),
    stepFunction: "generateTextStep",
  },
  "Generate Image": {
    importer: () => import("@/plugins/ai-gateway/steps/generate-image/step"),
    stepFunction: "generateImageStep",
  },
  Scrape: {
    importer: () => import("@/plugins/firecrawl/steps/scrape/step"),
    stepFunction: "firecrawlScrapeStep",
  },
  Search: {
    importer: () => import("@/plugins/firecrawl/steps/search/step"),
    stepFunction: "firecrawlSearchStep",
  },
  "Create Ticket": {
    importer: () => import("@/plugins/linear/steps/create-ticket/step"),
    stepFunction: "createTicketStep",
  },
  "Find Issues": {
    importer: () => import("@/plugins/linear/steps/find-issues/step"),
    stepFunction: "findIssuesStep",
  },
  "Send Email": {
    importer: () => import("@/plugins/resend/steps/send-email/step"),
    stepFunction: "sendEmailStep",
  },
  "Send Slack Message": {
    importer: () => import("@/plugins/slack/steps/send-slack-message/step"),
    stepFunction: "sendSlackMessageStep",
  },
  "Create Chat": {
    importer: () => import("@/plugins/v0/steps/create-chat/step"),
    stepFunction: "createChatStep",
  },
  "Send Message": {
    importer: () => import("@/plugins/v0/steps/send-message/step"),
    stepFunction: "sendMessageStep",
  },
  "S3 Upload": {
    importer: () => import("@/extensions/plugins/aws/steps/s3-upload/step"),
    stepFunction: "s3UploadStep",
  },
  "Lambda Invoke": {
    importer: () => import("@/extensions/plugins/aws/steps/lambda-invoke/step"),
    stepFunction: "lambdaInvokeStep",
  },
  "Blob Upload": {
    importer: () => import("@/extensions/plugins/azure/steps/blob-upload/step"),
    stepFunction: "blobUploadStep",
  },
  "Cloud Storage Upload": {
    importer: () =>
      import("@/extensions/plugins/gcp/steps/storage-upload/step"),
    stepFunction: "storageUploadStep",
  },
  "Create Scraping Job": {
    importer: () =>
      import(
        "@/extensions/plugins/lead-scraper/steps/create-scraping-job/step"
      ),
    stepFunction: "createScrapingJobStep",
  },
  "Get Scraping Job": {
    importer: () =>
      import("@/extensions/plugins/lead-scraper/steps/get-scraping-job/step"),
    stepFunction: "getScrapingJobStep",
  },
  "List Leads": {
    importer: () =>
      import("@/extensions/plugins/lead-scraper/steps/list-leads/step"),
    stepFunction: "listLeadsStep",
  },
  "Get Lead Stats": {
    importer: () =>
      import("@/extensions/plugins/lead-scraper/steps/get-lead-stats/step"),
    stepFunction: "getLeadStatsStep",
  },
  "Download Results": {
    importer: () =>
      import("@/extensions/plugins/lead-scraper/steps/download-results/step"),
    stepFunction: "downloadResultsStep",
  },
  "Find Documents": {
    importer: () =>
      import("@/extensions/plugins/mongodb/steps/find-documents/step"),
    stepFunction: "findDocumentsStep",
  },
  "Get Value": {
    importer: () => import("@/extensions/plugins/redis/steps/get-value/step"),
    stepFunction: "getValueStep",
  },
};

/**
 * Get a step importer for an action type
 */
export function getStepImporter(actionType: string): StepImporter | undefined {
  return PLUGIN_STEP_IMPORTERS[actionType];
}
